serial:
  port: /dev/ttyUSB0
  baud: 115200
mqtt:
  ip: localhost
  port: 1883
network:
  wifi:
    state: 'on'
    ssid: rp-link
    password: meowkissme
  eth0:
    mode: static
    ip: jjjjjjj
    mask: jhhgg
    gateway: None
